# spec:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    TZ: "America/New_York date"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Install started on `date`
      - npm install -g @typescript-eslint/parser typescript eslint @typescript-eslint
  build:
    commands:
      - echo Build started on `date`
      - npx eslint '**/*.ts'
